version: '3.4'

services:
  antivirus:
    image: mkodockx/docker-clamav:alpine

  users-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1401:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"

  physical-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1402:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"


  smartenergy.users:
    image: ${DOCKER_REGISTRY-}smartenergyusers
    build:
      context: .
      dockerfile: SmartEnergy.Users/Dockerfile
    ports:
      - "6969:80"
      - "44372:443"
    depends_on:
      - users-db


  smartenergy.physical:
    image: ${DOCKER_REGISTRY-}smartenergyphysical
    build:
      context: .
      dockerfile: SmartEnergy.Physical/Dockerfile
    ports:
      - "6970:80"
      - "44373:443"
    depends_on:
      - physical-db

