version: '3.4'

services:
  antivirus:
    image: mkodockx/docker-clamav:alpine

  users-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1401:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"

  physical-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1402:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"


  smartenergy.users:
    image: ${DOCKER_REGISTRY-}smartenergyusers
    build:
      context: .
      dockerfile: SmartEnergy.Users/Dockerfile
    ports:
      - "5201:50001"
      - "6969:80"
      - "44372:443"
    depends_on:
      - users-db
      - placement
    networks:
      - hello-dapr
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=smartenergyusers
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/smartenergyusers.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  smartenergy.users-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "smartenergyusers", "-dapr-http-port", "3500",  "-app-port", "80", "-placement-host-address", "placement:50006" ]
    depends_on:
      - smartenergy.users
    network_mode: "service:smartenergy.users"


  smartenergy.physical:
    image: ${DOCKER_REGISTRY-}smartenergyphysical
    build:
      context: .
      dockerfile: SmartEnergy.Physical/Dockerfile
    ports:
      - "5200:50001"
      - "6970:80"
      - "44373:443"
    depends_on:
      - physical-db
      - placement
    networks:
      - hello-dapr
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=smartenergyphysical
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/smartenergyphysical.pfx
    volumes:
      - ~/.aspnet/https:/https:ro


  smartenergy.physical-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "smartenergyphysical", "-dapr-http-port", "3501", "-app-port", "80", "-placement-host-address", "placement:50006"]
    depends_on:
      - smartenergy.physical
    network_mode: "service:smartenergy.physical"



  #smartenergy.documents:
  #  image: ${DOCKER_REGISTRY-}smartenergydocuments
  #  build:
  #    context: .
  #    dockerfile: SmartEnergy.Documents/Dockerfile
   # ports:
  #    - "6971:80"
  #    - "44374:443"
  #  depends_on:
  #    - documents-db
   #   - placement
   # networks:
    #  - hello-dapr
##
 # documents-db:
 #   image: mcr.microsoft.com/mssql/server
 #   ports:
   #   - "1403:1433"
  #  environment:
   #   ACCEPT_EULA: "Y"
   #   SA_PASSWORD: "Your+password123"

 # smartenergy.documents-dapr:
  #  image: "daprio/daprd:latest"
  #  command: [ "./daprd", "-app-id", "smartenergydocuments", "-dapr-http-port", "3502", "-app-port",  "443", "-placement-host-address", "placement:50006", "-app-ssl" ]
  #  depends_on:
   #   - smartenergy.documents
   # network_mode: "service:smartenergy.documents"
##
############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr

############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - hello-dapr

networks:
    hello-dapr:

