version: '3.4'

services:
  smartenergy.users:
    ports:
      - "80"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=smartenergyusers
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/smartenergyusers.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  smartenergy.physical:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=smartenergyphysical
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/smartenergyphysical.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "80"
      - "443"

  #smartenergy.documents:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
 #     - "80"
  #    - "443"
 #   volumes:
 #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
